Images initial cleanup plus a regression fixup: EEE
EEEEEE if filedata isabs....

Reverted the except (yak) as it blows for a shortcut to a python file and who
knows what else:

Traceback (most recent call last):
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 398, in main
    basher.InitLinks()
  File "bash\basher\links.py", line 734, in InitLinks
    InitStatusBar()
  File "bash\basher\links.py", line 176, in InitStatusBar
    for pth, icon, description in init_app_links(dirApps, badIcons, iconList):
  File "bash\env.py", line 234, in init_app_links
    icon, idex = _get_default_app_icon(idex, target)
  File "bash\env.py", line 176, in _get_default_app_icon
    icon, idex = filedata.split(u',')
ValueError: need more than 1 value to unpack

Debugger:

icon_path = {str} 'Python.File'
filedata = {unicode} u'C:\\_\\Python27\\DLLs\\py.ico'

EEEEEE if filedata isabs....

@@ -184,3 +184,3 @@ def _get_default_app_icon(idex, target):
                     break
-    except OSError: # WAS except:
+    except:
         deprint(_(u'Error finding icon for %s:') % target.s, traceback=True)

Introduced in b7a27675d74ca8980b0835aabd540d54e19c31b1