Fix for Recalculate Record Counts: EEE
Traceback (most recent call last):
  File "bash\balt.py", line 1832, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 116, in Execute
    modFile.load(True)
  File "bash\mod_files.py", line 268, in load
    self._convert_fids(to_long=True)
  File "bash\mod_files.py", line 345, in _convert_fids
    target_top.convertFids(mapper, to_long)
  File "bash\brec\record_groups.py", line 153, in convertFids
    raise AbstractError(u'convertFids not implemented')
bash.exception.AbstractError: convertFids not implemented

Mopy/bash/basher/mod_links.py: went ahead and loaded record types so
MobObject is called - but maybe not convert fids in this case? EEE

Mopy/bash/bosh/__init__.py:
comments from 27e65c64535a9b16d62208771c3863b6c55fe720 not needed since
42746d52e7740a2ed5e85bb48637ca14ba4dad4f

I run accross this trying to finalize the getNumRecords fix -
this lead to LoadFactory and the rest of this branch. Turns out that the
MobBase.getNumRecords was only (?) called in this menu that was broken
(since f8678228fe82c999e4b5d2645b1494109dbac459 ?) - need to verify

BROKEN:

Traceback (most recent call last):
  File "bash\balt.py", line 1832, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 120, in Execute
    topType, block.getNumRecords()))
  File "bash\brec\record_groups.py", line 1181, in getNumRecords
    count += 1 + len(self.getUsedBlocks()) + len(
  File "bash\brec\record_groups.py", line 1128, in getUsedBlocks
    return {x.getBsb()[0] for x in self.cellBlocks}
  File "bash\brec\record_groups.py", line 1128, in <setcomp>
    return {x.getBsb()[0] for x in self.cellBlocks}
  File "bash\brec\record_groups.py", line 892, in getBsb
    baseFid = cell.fid & 0x00FFFFFF
TypeError: unsupported operand type(s) for &: 'tuple' and 'int'

FFF SSS: EEE

Well yes don't convert fids in this case EEE should be changed to a
display log - wgy we write those in the bugdump

@@ -113,5 +113,5 @@ class Mod_RecalcRecordCounts(OneItemLink):
     def Execute(self):
-        loadFactory = mod_files.LoadFactory(True, *MreRecord.type_class.values())
+        loadFactory = mod_files.LoadFactory(True)
         modFile = mod_files.ModFile(self._selected_info, loadFactory)
-        modFile.load(True)
+        modFile.load(True, do_map_fids=False)
         for topType, block in sorted(modFile.tops.iteritems(),

Now are the counts right? EEE see next
Cobl main

mod_links.py  120 Execute: ACTI GRUP has 111 records
mod_links.py  120 Execute: ALCH GRUP has 39 records
mod_links.py  120 Execute: AMMO GRUP has 17 records
mod_links.py  120 Execute: APPA GRUP has 2 records
mod_links.py  120 Execute: BOOK GRUP has 222 records
mod_links.py  120 Execute: CELL GRUP has 178 records
mod_links.py  120 Execute: CLOT GRUP has 8 records
mod_links.py  120 Execute: CONT GRUP has 113 records
mod_links.py  120 Execute: CREA GRUP has 2 records
mod_links.py  120 Execute: EFSH GRUP has 16 records
mod_links.py  120 Execute: ENCH GRUP has 70 records
mod_links.py  120 Execute: EYES GRUP has 153 records
mod_links.py  120 Execute: FACT GRUP has 25 records
mod_links.py  120 Execute: FLOR GRUP has 3 records
mod_links.py  120 Execute: GLOB GRUP has 61 records
mod_links.py  120 Execute: GMST GRUP has 2 records
mod_links.py  120 Execute: HAIR GRUP has 162 records
mod_links.py  120 Execute: INGR GRUP has 181 records
mod_links.py  120 Execute: LIGH GRUP has 2 records
mod_links.py  120 Execute: LVLI GRUP has 1073 records
mod_links.py  120 Execute: MISC GRUP has 478 records
mod_links.py  120 Execute: NPC_ GRUP has 2 records
mod_links.py  120 Execute: QUST GRUP has 64 records
mod_links.py  120 Execute: RACE GRUP has 8 records
mod_links.py  120 Execute: SCPT GRUP has 465 records
mod_links.py  120 Execute: SOUN GRUP has 3 records
mod_links.py  120 Execute: SPEL GRUP has 136 records
mod_links.py  120 Execute: STAT GRUP has 24 records
mod_links.py  120 Execute: WEAP GRUP has 110 records