Squashed commit of inf-fixes:
commit 2efc8653dd06bbdcecc50b1b48731e38478e08c1
Author: Infernio <infernio@icloud.com>
Date:   Fri Apr 17 03:03:16 2020 +0200

    Fix Dump Translator, was completely broken

    Not only was _find_all_bash_modules broken, dump_translator didn't even
    *begin* to handle encodings correctly. Reworked it to use binary modes
    for everything and to only encode/decode what's actually necessary, with
    the encodings specified by the translation files.

    Tested with German, Chinese (Traditional) and Russian.

    Mopy/bash/ScriptParser.py:
    Random typo, was the first in the translation files I opened and that
    typo glared me in the face :P

commit 31eea2f195e3894fdf536a64fc373315f6ccf813
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 13:46:03 2020 +0200

    Notify BAIN when ghosting or renaming plugins RRR

    To reproduce:
     1. Make sure Auto-Ghosting is on
     2. File.. > New Mod
     3. Switch to Installers tab

    You should get something like this:

    Traceback (most recent call last):
      File "bash\basher\__init__.py", line 3614, in OnShowPage
        refresh_target=load_order.using_ini_file())
      File "bash\balt.py", line 911, in _conversation_wrapper
        return func(*args, **kwargs)
      File "bash\basher\__init__.py", line 2962, in ShowPanel
        scan_data_dir)
      File "bash\balt.py", line 911, in _conversation_wrapper
        return func(*args, **kwargs)
      File "bash\bosh\bain.py", line 1521, in _projects_walk_cache_wrapper
        return func(self, *args, **kwargs)
      File "bash\basher\__init__.py", line 3007, in _refresh_installers_if_needed
        do_refresh = self.listData.refreshTracked()
      File "bash\bosh\bain.py", line 2134, in refreshTracked
        self.data_sizeCrcDate[key] = (apath.size,apath.crc,apath.mtime)
      File "bash\bolt.py", line 629, in size
        return os.path.getsize(self._s)
      File "C:\Python27-32\lib\genericpath.py", line 57, in getsize
        return os.stat(filename).st_size
    WindowsError: [Error 2] The system cannot find the file specified: u'G:\\steam\\steamapps\\common\\Enderal\\Data\\New Mod.esp'

    This fixes it by enhancing our notify_external API to allow us to tell
    BAIN about renames. Of course, this isn't really the best place for it -
    once again comes down to copyTo/moveTo APIs. Ref # 336. <--- RRR

    Mopy/bash/basher/__init__.py:
    Threw in a fixup for a random crash I got but couldn't reproduce.
    Probably wx quirks.

    Mopy/bash/bosh/__init__.py:
    Some 'renames' renames :P

commit 0626e1dd3f5f7bb758f5c80cbef9b978b6ce9d00
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 12:30:19 2020 +0200

    Guess Dummy Masters flags based on extension

    Prevents creating .esm files without an ESM flag in Skyrim LE and
    earlier.

commit abc00631b2a103a0256089c93a59d808c64a4098
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 04:16:52 2020 +0200

    Make Nvidia Fog Fix Oblivion-only

    Blows on anything but Oblivion, and isn't necessary on anything but
    Oblivion anyways (probably not even necessary on Oblivion these
    days...).

commit b0e334da801fec7370ceab6f5672a7a092a3b850
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 03:55:29 2020 +0200

    Drop Undelete Refs and a bunch of cruft RRR

    This is all stuff that xEdit is really good at, and that we're really
    terrible at. So terrible that PBash was happily writing out the most
    corrupt plugins I have *ever* seen when you tried to use it.

    The remainder is either unused cruft or has been disabled for a long
    time now.

    Under # 173 <--- RRR

commit 95ebb351b40e34fab1596fddf78730f7b4192388
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 02:27:28 2020 +0200

    Drop Export/Import Stats link for Skyrim

    Starting raising errors in cb32315426e64989264be355cdbaa1bcb4139cd4, but
    it wasn't working properly before that either.

    The convertToLongFids() call introduced there works fine in the patcher
    where only readFromMod is used. However, it breaks the Import Stats link,
    which uses writeToMod. That method has to load with LoadFactory's
    keepAll feature, which will load all tops with MobBase. That means it
    can't do a blanket convertToLongFids() call, because MobBase does not
    implement convertFids, leading to this traceback:

    Traceback (most recent call last):
      File "bash\balt.py", line 1792, in __Execute
        self.Execute()
      File "bash\basher\mod_links.py", line 1935, in Execute
        changed = self._import(ext, textDir, textName, textPath)
      File "bash\basher\mod_links.py", line 1897, in _import
        changed = parser.writeToMod(self._selected_info)
      File "bash\parsers.py", line 1491, in writeToMod
        modFile.convertToLongFids()
      File "bash\parsers.py", line 4120, in convertToLongFids
        selfTops[type].convertFids(mapper,True)
      File "bash\record_groups.py", line 151, in convertFids
        raise AbstractError
    bash.exception.AbstractError: Abstract section called.

    Of course, we can't just not convert to long fids either - Otherwise we
    won't be able to handle critical effects. The only solution, for now, is
    to remove the Export/Import Stats links for Skyrim. Will be revisited in
    the parser ABC merge.

    Note that this once again goes to show that the whole ModFile API is a
    big footgun right now :)
    Ideally, we'd make ModFile.load automatically convert to long fids, and
    ModFile.save automatically convert back to short fids to avoid this
    whole debacle - see future tweak pooling merge for some more work in
    this direction.

    Threw in some stuff taken from future tweak pooling merge (
    bolt.floats_equal, unused load_unpack/load_UI dropped, etc.).

commit 023060f99c0ba31001d0e2940c22699e9484856a
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 02:20:19 2020 +0200

    Drop SCPT/QUST hardcoding in Import/Export Editor IDs

    Breaks games that don't have SCPT. Not sure why this was ever here, SCPT
    and QUST are in bush.game.simpleTypes anyways and the optional types
    argument for EditorIds.__init__ is never used (*cough* dropped in parser
    ABC *cough*). It's been there since the initial commit, too - so no way
    to figure out why.

commit cc90060115ae47609919f152c32864bbdca448b6
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 01:27:34 2020 +0200

    Fix PBash trying to merge CBash-only mods

    If you swap from a PBash to a CBash patch, then obviously the mergeable
    mods need to be refreshed, since CBash can merge more. However, the
    condition was checking if CBash was enabled, not if CBash was available
    at all. However, it's possible for a user to disable CBash through
    something like the -P CLI parameter. That would make the BP process use
    the cached CBash mergeability information for a PBash rebuild!

    Even worse, PBash just silently skips the record types it can't handle,
    leaving users with the impression that what they tried actually
    *worked*. If it blew up, it would at least be obvious that something is
    wrong :/

    As far as I can tell, the only good solution here is to issue a refresh
    on every Rebuild Patch for CBash games, whether CBash is enabled or not.
    Since almost everyone and their mother has CBash enabled for the only
    CBash game, this is going to be a noop change 99.9% of the time.

commit 405d6e875933f4e0b755a02432a1efa95e506e59
Author: Infernio <infernio@icloud.com>
Date:   Thu Apr 16 00:36:19 2020 +0200

    Fix outdated Nexus URL

    ...in Copy Mod Info and Create BOSS Report (we really should hide this
    for non-Oblivion games and add a Create LOOT Report link).

commit c6575403d35126a40e0c83b63aaa55b91d8c10db
Author: Infernio <infernio@icloud.com>
Date:   Wed Apr 15 23:15:03 2020 +0200

    Fix Clean Data removing one of the BP docs

    :facepalm:

commit 7e2cf20c200f7f703c68c4a4b5fda8afed65ec47
Author: Infernio <infernio@icloud.com>
Date:   Wed Apr 15 17:50:41 2020 +0200

    Rename Create New Project -> New Project

    ...and fix it not actually updating the dialog icon when selecting only
    a masterless ESP. Actually, I only wanted to do that, but then decided
    to rename it as well for consistency with the Mods tab (Files.. > New
    Mod etc.).

commit 79dc19a2dbab1d2342e08194d6d8f82b6300b1c5
Author: Infernio <infernio@icloud.com>
Date:   Wed Apr 15 17:17:44 2020 +0200

    Rename Load Order -> Active Mods

    IIRC I changed this to Load Order, but that's clearly not right and is
    only going to confuse people (as it already did one person on Discord).

commit b80cf1622eca86fd08238e122043b618e58cdbc0
Author: Infernio <infernio@icloud.com>
Date:   Wed Apr 15 16:43:20 2020 +0200

    Regression: Fix CRC calculation error

    Introduced in de50126400f7bf2c2cfdfd90680cc26a7620a032.

    progress may be None here. Caused an error when using 'Copy Conflicts to
    Project' and probably was the cause of the startup error reported on
    Discord.

commit 36f5376df4e542b0d85d50da3e3cf7b40b4e712f
Author: Infernio <infernio@icloud.com>
Date:   Wed Apr 15 16:09:38 2020 +0200

    Drop Redate command from Installers tab

    Introduced in 92691409567ce020c6958325ee8c4bd8c9e820cc.

    Forgot to remove this from InitInstallersLinks when I removed it from
    the other tabs. Also updated some parts of the documentation that I
    forgot to update when I reverted the Redate etc. changes and
    fixed/clarified that deleting through WB does *not* permanently delete
    files, it just moves them to the recycling bin.